### ISSUE TITLE
Allow `size` param to be specified for `collections`

### ISSUE THREAD

**Issue by mzikherman** [artsy/kaws#54]
This is so that when retrieving collections for KAWS (for example), we can just retrieve a few, and not all of them. Especially if you want to also retrieve artworks for each collection (hitting ES), we should be careful not to overfetch.

**Comment by eessex** [comment]
You should make a jira ticket for this!

**Comment by mzikherman** [comment]
Actually addressed in https://github.com/artsy/kaws/pull/62

**Comment by eessex** [comment]
Cool gonna close this!
